
version: '2.1'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack}"
    image: localstack/localstack
    ports:
      - "4566-4599:4566-4599"
      #- "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      #- SERVICES=${SERVICES- }
      - SERVICES=secretsmanager
      #- DEBUG=${DEBUG- }
      - DEBUG=1
      - DATA_DIR=${DATA_DIR- }
      #- DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

    redis:
      image: "redis:6.0.5-alpine"
      ports:
        - "6379:6379"
    redisinsight:
      image: "redislabs/redisinsight"
      ports:
        - "8001:8001"


# cd /Users/diegolucas/Downloads/aws-master/app-redis/src/main/resources
#TMPDIR=/private$TMPDIR docker-compose up

#Criar secret depois do container de pe
# aws --endpoint-url=http://localhost:4566 secretsmanager create-secret --name dev/redis/auth --description "redis-secret-test" --secret-string file://redis-secret.json

#docker run -p 8089:8089 diegol/aws-config-server:0.0.1-SNAPSHOT
#docker run -p 8080:8080 diegol/app-redis:0.0.1-SNAPSHOT


